// <auto-generated />
using CateringSaaS.Shared.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace CateringSaaS.Shared.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261007120000_AddWorkspaceNotifications")]
    partial class AddWorkspaceNotifications
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            // Target model is maintained in AppDbContextModelSnapshot.
            // This designer stub keeps EF tooling aware of the migration id.
#pragma warning restore 612, 618
        }
    }
}
